x_survey_render() {
  printf '<!-- Generated by `xdh survey`. Machine-derived facts only: no judgement, no prose.\n'
  printf '     Read this instead of walking the tree. Open individual files only where a\n'
  printf '     decision actually depends on their contents. -->\n\n'
  printf '# Project survey\n\n'
  x_survey_section_repo
  x_survey_section_layout
  x_survey_section_types
  x_survey_section_entry
  x_survey_section_docs
  x_survey_section_tests
  x_survey_section_devex
  x_survey_section_graph
  x_survey_section_hotspots
}

# Last-resort cap. Sections are individually bounded, so this should not fire on
# an ordinary repository; when it does, a truncated survey with an explicit
# marker beats silently handing the agent an unbounded document.
x_survey_truncate() {
  local file=$1 bytes
  bytes=$(wc -c < "$file" | tr -d ' ')
  (( bytes <= X_SURVEY_MAX_BYTES )) && return 0
  local keep=$(( X_SURVEY_MAX_BYTES - 80 ))
  {
    dd if="$file" bs=1 count="$keep" 2>/dev/null
    printf '\n\n<!-- survey truncated at %s bytes -->\n' "$X_SURVEY_MAX_BYTES"
  } | x_atomic_write "$file"
}

x_survey_ensure() {
  local force=0
  while (( $# )); do
    case $1 in
      --force) force=1; shift ;;
      *) x_die "survey ensure: unknown option '$1'" ;;
    esac
  done

  x_ensure_dev_hub
  # `survey ensure` is a supported first xdh command. Register the runtime ignore
  # before computing the key or rendering, otherwise the survey writes its own
  # untracked `.dev-hub/` and reports that residue as a project change.
  x_ensure_gitignore >/dev/null
  local dir file keyfile graphfile key state
  dir=$(x_survey_dir); file=$(x_survey_file); keyfile=$(x_survey_keyfile); graphfile=$(x_survey_graphfile)
  mkdir -p "$dir"
  key=$(x_survey_key)

  if (( ! force )) && [[ -f $file && -f $keyfile && -f $graphfile ]] && [[ $(cat -- "$keyfile") == "$key" ]]; then
    state=fresh
    x_survey_graph_load || { X_SURVEY_GRAPH=absent; X_SURVEY_NAV=files; X_SURVEY_GRAPH_SYMBOLS=0; }
    x_survey_graph_validate_cached
  else
    # Rebuilding means the commit or working content moved — the one moment a
    # sync is worth its cost. It runs before render so the Code graph section
    # reports post-sync numbers, and the result is persisted with this cache.
    x_survey_graph_probe 1
    x_survey_render | x_atomic_write "$file"
    x_survey_truncate "$file"
    printf '%s' "$key" | x_atomic_write "$keyfile"
    x_survey_graph_save
    state=rebuilt
  fi

  x_emit X_SURVEY_FILE "$file"
  x_emit X_SURVEY_STATE "$state"
  x_emit X_SURVEY_HEAD "$(git -C "$X_MAIN_ROOT" rev-parse HEAD 2>/dev/null || printf 'no-head')"
  x_emit X_SURVEY_BYTES "$(wc -c < "$file" | tr -d ' ')"
  x_emit X_SURVEY_NAV "${X_SURVEY_NAV:-files}"
  x_emit X_SURVEY_GRAPH "${X_SURVEY_GRAPH:-absent}"
  x_emit X_SURVEY_GRAPH_SYMBOLS "${X_SURVEY_GRAPH_SYMBOLS:-0}"
}

# Report where the survey lives without building it, so a caller can decide
# whether to spend the rebuild.
x_survey_path() {
  x_resolve_paths
  local file keyfile graphfile freshness
  file=$(x_survey_file); keyfile=$(x_survey_keyfile); graphfile=$(x_survey_graphfile)
  x_emit X_SURVEY_FILE "$file"
  if [[ -f $file ]]; then
    if [[ -f $keyfile && $(cat -- "$keyfile" 2>/dev/null) == "$(x_survey_key)" ]]; then
      freshness=fresh
    else
      freshness=stale
    fi
    x_emit X_SURVEY_STATE "$freshness"
    x_emit X_SURVEY_BYTES "$(wc -c < "$file" | tr -d ' ')"
  else
    freshness=absent
    x_emit X_SURVEY_STATE absent
    x_emit X_SURVEY_BYTES 0
  fi

  # Report-only: never sync. For a fresh cache, preserve the cached freshness
  # decision (especially `stale` after a failed sync); for an absent/stale cache,
  # a current probe is safe because this command does not route work itself.
  if [[ $freshness == fresh && -f $graphfile ]] && x_survey_graph_load; then
    x_survey_graph_validate_cached
  else
    x_survey_graph_probe 0
  fi
  x_emit X_SURVEY_NAV "${X_SURVEY_NAV:-files}"
  x_emit X_SURVEY_GRAPH "${X_SURVEY_GRAPH:-absent}"
}
